import turtle             
my_window = turtle.Screen() 
my_window.bgcolor("#D4292F")
my_pen = turtle.Turtle()      
my_pen.forward(150)
my_pen.left(90)
my_pen.forward(75)
my_pen.color("white")
my_pen.pensize(50)
turtle.done()
